name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Run workflow when pushing to main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t harshan536/node-v .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push harshan536/node-v
deploy:
    build-and-push:
    runs-on: self-hosted
    steps:
      # Step 1: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 2: Pull the Docker image
      - name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/node-v

      # Step 3: Stop and remove any existing container
      - name: Stop and remove old container
        run: |
          docker stop compassionate_swirles || true
          docker rm compassionate_swirles|| true

      # Step 4: Run the Docker container
      - name: Run Docker container
        run: |
          docker run -d --name node-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/node-v
